0glabs/0g-storage-client

- contract/contract.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zero-gravity-labs/zerog-storage-client/2)
> Add method for submission to calculate root hash

- common/blockchain/rpc.go
- transfer/uploader.go
- transfer/uploader_dup_file.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zero-gravity-labs/zerog-storage-client/3)
> chore: function visibility, default retry option

- node/types.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zero-gravity-labs/zerog-storage-client/4)
> Add fields for rpc struct

- contract/contract.go
- transfer/uploader.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/6)
> Supports fixed price fee

- cmd/generate_file.go
- cmd/root.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/7)
> update cli to gen tmp file

- common/blockchain/rpc.go
- common/util/reminder.go
- transfer/uploader.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/8)
> Enhance log for time consuming operations

- transfer/uploader.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/9)
> enhance log when storage node sync submission from blockchain

- cmd/download.go
- gateway/local_apis.go
- transfer/download_parallel.go
- transfer/downloader.go
- transfer/uploader.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/11)
> feat: download by shard

- cmd/indexer.go
- common/util/rpc.go
- indexer/api.go
- indexer/client.go
- indexer/types.go
- node/client.go
- node/types.go
- transfer/uploader.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/13)
> Indexer service skeleton

- cmd/download.go
- gateway/local_apis.go
- indexer/api.go
- indexer/types.go
- indexer/types_test.go
- node/types.go
- transfer/downloader.go
- transfer/uploader.go
- transfer/uploader_dup_file.go
- transfer/uploader_parallel.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/14)
> feat: select using segment tree

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/19)
> Change name to 0G in README.md

- cmd/indexer.go
- common/shard/types.go
- common/shard/types_test.go
- indexer/api.go
- indexer/client.go
- indexer/node_manager.go
- indexer/types.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/24)
> Supports to discover peers from storage node

- indexer/api.go
- indexer/client.go
- indexer/ip_locatoin.go
- indexer/node_manager.go
- indexer/types.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/25)
> Supports to detect ip location of all storage nodes

- .gitignore
- cmd/indexer.go
- indexer/ip_locatoin.go
- indexer/node_manager.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/26)
> Supports ip location cache

- indexer/api.go
- indexer/client.go
- indexer/ip_locatoin.go
- indexer/node_manager.go
- indexer/types.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/27)
> Enhance ip location rpc for geo charts

- common/util/rpc.go
- go.mod
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/28)
> Supports cors

- indexer/node_manager.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/29)
> Detect IP location of trusted node

- indexer/ip_locatoin.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/30)
> Cache ip location only when all fields retrieved

- cmd/indexer.go
- indexer/ip_locatoin.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/31)
> Supports to specify access token to retrieve ip loc

- indexer/ip_location.go
- indexer/node_manager.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/33)
> enhance logs

- cmd/download.go
- cmd/kv_read.go
- cmd/kv_write.go
- cmd/root.go
- cmd/upload.go
- common/blockchain/rpc.go
- tests/batch_upload_test.py
- tests/go_tests/batch_upload_test/main.go
- transfer/uploader.go
- Add rpc retry and timeout args in root cli
- Add nonce args in upload related cli
- Add nonce in upload interface
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/44)
> feat: more options

- indexer/client.go
- tests/go_tests/batch_upload_test/main.go
- transfer/uploader.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/48)
> feat: upload files in parallel in batch upload

- indexer/file_location_cache.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/50)
> fix: check nil info

- cmd/kv_write.go
- cmd/upload.go
- tests/go_tests/batch_upload_test/main.go
- tests/go_tests/indexer_test/main.go
- transfer/uploader.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/53)
> refactor: FinalityRequired option

- cmd/upload.go
- cmd/upload_dir.go
- transfer/dir/fs.go
- transfer/dir/fs_test.go
- transfer/uploader.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/46)
> feat: Add support for uploading folders to 0gStorage

- common/parallel/rpc.go
- common/parallel/serial.go
- common/parallel/serial_test.go
- core/dataflow.go
- core/flow.go
- go.mod
- indexer/node_manager.go
- transfer/download_parallel.go
- transfer/uploader.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/54)
> Opt indexer perf with parallel rpc execution

- cmd/download.go
- cmd/download_dir.go
- indexer/client.go
- transfer/dir/fs.go
- transfer/download/downloading_dir.go
- transfer/download_dir.go
- transfer/downloader.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/47)
> feat: Add support for downloading folders to 0gStorage

- cmd/diff_dir.go
- go.mod
- transfer/dir/diff.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/49)
> feat: Add folder diff command for comparing with 0gStorage

- transfer/download/downloading_dir.go
- transfer/download_dir.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/55)
> fix: Correct symlink creation/update logic in dir download

- node/client_admin.go
- node/client_kv.go
- node/client_zgs.go
- node/rpc_client.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/56)
> public provider

- indexer/gateway/download.go
- indexer/gateway/server.go
- transfer/dir/fs.go
- transfer/dir/fs_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/57)
> feat: add dir path file download support in indexer gateway

- cmd/kv_write.go
- cmd/upload.go
- cmd/upload_dir.go
- common/shard/types.go
- common/shard/types_test.go
- indexer/client.go
- indexer/file_location_cache.go
- transfer/uploader.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/60)
> feat: more selection logic

- transfer/uploader.go
- transfer/uploader_parallel.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/61)
> Implement retry on submission failures

- indexer/api.go
- indexer/ip_location.go
- indexer/node_manager.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/65)
> Fix indexer ip

- cmd/indexer.go
- common/shard/types.go
- common/shard/types_test.go
- core/dataflow.go
- indexer/gateway/download.go
- indexer/gateway/server.go
- indexer/gateway/upload.go
- transfer/download_parallel.go
- transfer/uploader.go
- transfer/uploader_parallel.go
- Implement `FileSegmentUploader` for parallel batch file segment uploads
- Refactor common segment calculation logic for reuse and clarity
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/64)
> feat: add segment upload RESTful API for indexer gateway

- README.md
- indexer/gateway/upload.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/66)
> docs: update docs and deprecate `multipart/form-data` for indexer gateway

- gateway/local_apis.go
- indexer/gateway/download.go
- node/types.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/68)
> Add file pruned info in FileInfo

- indexer/client.go
- tests/client_test_framework/test_framework.py
- tests/go_tests/segment_upload_test/main.go
- tests/segment_upload_test.py
- Improve indexer test stub setup to wait for port being available.
- Add integration tests for the file segment uploading.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/69)
> feat(indexer-client): support file segment uploading

- README.md
This pull request includes updates to the `README.md` file to correct documentation links for better accuracy and user guidance.
Documentation updates:
* Updated the link for more details on the Go implementation for the client to interact with storage nodes in the 0G Storage network.
* Updated the link for more details on the RPC API documentation for indexing storage nodes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/73)
> replaced the broken links

- common/api/controller.go
- gateway/local_apis.go
- indexer/gateway/download.go
- indexer/gateway/status.go
- indexer/gateway/upload.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/80)
> Hotfix err json

- indexer/gateway/controller.go
- indexer/gateway/download.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/86)
> fix: close storage client after use in indexer rest api

- contract/contract.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/90)
> fix issues

- cmd/download.go
- cmd/generate_file.go
cmd/download.go
`simutanously` - `simultaneously`
cmd/generate_file.go
`Overrite` - `Overwrite`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/85)
> fix errors in function

- tests/utility/signature_utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/83)
> Fix incorrect dockstring for the functions

- cmd/kv_write.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/82)
> fix: errors in parameters and variables

- contract/contract.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/93)
> make contract usable by 3rd tools

- cmd/upload.go
- common/blockchain/rpc.go
- contract/contract.go
- tests/go_tests/segment_upload_test/main.go
- tests/test_framework/test_framework.py
- tests/test_framework/zg_node.py
- transfer/uploader.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/96)
> tx retry with higher gas price

- indexer/file_location_cache.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/98)
> fix indexer cache

- contract/contract.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/99)
> remove log

- core/merkle/proof.go
- indexer/gateway/upload.go
- indexer/ip_location.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/95)
> docs: correct spelling errors 

- .github/workflows/tests.yml
- gateway/local_apis.go
- indexer/api.go
- indexer/gateway/controller.go
- node/client_zgs.go
- tests/go_tests/indexer_test/main.go
- tests/go_tests/segment_upload_test/main.go
- tests/test_framework/zgs_node.py
- tests/utility/build_binary.py
- transfer/downloader.go
- transfer/uploader.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/102)
> update node api

- indexer/gateway/upload.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/105)
> add default for upload method for restapi

- transfer/uploader.go
- transfer/uploader_parallel.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-storage-client/106)
> add minor logs
